// Generated by ego.
// DO NOT EDIT

package tpl
import (
"fmt"
"html"
"io"
)
var _ = fmt.Sprint("") // just so that we can keep the fmt import for now
//line footer.ego:1
 func Footer(w io.Writer, p *Page) error  {
//line footer.ego:2
_, _ = io.WriteString(w, "\n<div>")
//line footer.ego:2
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  p.Year )))
//line footer.ego:2
_, _ = io.WriteString(w, " Year</div>\n</body>\n</html>")
return nil
}
//line header.ego:1
 func Header(w io.Writer, p *Page) error  {
//line header.ego:2
_, _ = io.WriteString(w, "\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n\t<meta charset=\"UTF-8\">\n\t<title>")
//line header.ego:6
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  p.Title )))
//line header.ego:6
_, _ = io.WriteString(w, " Year</title>\n</head>\n<body>")
return nil
}
//line home.ego:1
 func Home(w io.Writer, p *Page) error  {
//line home.ego:2
_, _ = io.WriteString(w, "\n\n")
//line home.ego:3
 Header(w, p) 
//line home.ego:4
_, _ = io.WriteString(w, "\n<h1>Hello ")
//line home.ego:4
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  p.Title )))
//line home.ego:4
_, _ = io.WriteString(w, "</h1>\n\n<p>Here's a list of your favorite colors:</p>\n\n<ul>\n\t")
//line home.ego:9
 for _, colorName := range p.FavoriteColors { 
//line home.ego:10
_, _ = io.WriteString(w, "\n\t<li>")
//line home.ego:10
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  colorName )))
//line home.ego:10
_, _ = io.WriteString(w, "</li>\n\t")
//line home.ego:11
 } 
//line home.ego:12
_, _ = io.WriteString(w, "\n</ul>\n")
//line home.ego:13
 Footer(w, p) 
//line home.ego:14
_, _ = io.WriteString(w, "\n")
return nil
}
